---
- name: Loops
  hosts: all
  remote_user: ansible
  tasks:
  - name: Simple Loop
    debug: msg="{{item}}"
    with_items:
      - "ist"
      - "das"
      - "simpel"

- name: Loops
  hosts: all
  remote_user: ansible
  tasks:
  - name: Nested Loop
    debug: msg="{{item[0]}} {{item[1]}}"
    with_nested:
      - ["ist", "simpel"]
      - ["das"]

- name: Dictionary
  hosts: all
  remote_user: ansible
  tasks:
  - name: Loop on Dictionary
    debug: msg="{{item.key}} {{item.value.item}}"
    with_dict: '{{countries}}'

- name: Inventory
  hosts: all
  remote_user: ansible
  tasks:
  - name: Loop on Dictionary
    debug: msg="{{item.key}} {{item.value.item}}"
    with_dict: '{{countries}}'
