Vagrant.configure("2") do |config|
  config.vm.box = "windows10"
  config.vm.guest = :windows

  # Configure Vagrant to use WinRM instead of SSH
  config.vm.communicator = "winrm"

  # Configure WinRM Connectivity
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"

  config.vm.provider "virtualbox" do |virtualbox|
     virtualbox.name = "ControlMachine"
     virtualbox.gui = true
     virtualbox.memory = 2048
     virtualbox.cpus = 4
   end

end