---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600
  become: true
  tags:
    - install

- name: Installiere haproxy in aktueller Version
  apt: name=haproxy state=latest
  become: true
  tags:
    - install

- name: Starte haproxy
  service: name=apache2 state=started enabled=yes
  tags:
    -install
