Vagrant.configure("2") do |config|

  config.vm.box = "windows_2016_ansible_virtualbox"
  config.vm.network "forwarded_port", guest: 5986, host: 55986, host_ip: "127.0.0.1", id: "winrm-ssl"

  config.vm.provider "virtualbox" do |virtualbox|
     virtualbox.name = "AnsibleWsWindows"
     virtualbox.gui = true
     virtualbox.memory = 2048
     virtualbox.cpus = 4
   end

end