Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = false
    #config.vm.network "forwarded_port", guest: 22, host: 2222, host_ip: "127.0.0.1", id: "ssh"

    config.vm.provider :virtualbox do |virtualbox|
       virtualbox.name = "LinuxUbuntu"
       virtualbox.gui = true
       virtualbox.memory = 2048
       virtualbox.cpus = 2
       virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
       virtualbox.customize ["modifyvm", :id, "--vram", "32"]
    end

end