---
#  hosts: all
#  remote_user: ansible
#  tasks:
#  - name: Debian?
#    debug: msg="Hallo von Debian"
#    when: ansible_os_family=="Debian"
#
#  - name: Centos?
#    debug: msg="Hallo von Centos"
#    when: ansible_os_family=="Centos"



- name: Installiere Webserver
  hosts: all
  remote_user: ansible
  become: true
  tasks:
  - name: Setze Distributionsvariablen Debian
    set_fact:
      webserver: "var"

  - name: Setze Distributionsvariablen Centos
    debug: msg="1"
    when: webserver

  - name: Starte webserver
    debug: msg="2"
    when: webserver=="true"
