---
- name: Register
  hosts: ffm
  remote_user: ansible
  tasks:
  - name: Debugging!!
    debug: msg="Test debugging!"

  - name: Uptime prüfen
    shell: /usr/bin/uptime
    register: myuptime

  - name: Uptime Debugging
    debug: var=myuptime

  #- name: Uptime Debugging als msg
  #  debug: msg={{myuptime}}

  - name: Uptime stdout
    debug: msg="Meine Uptime Details:{{ myuptime.stdout }}"
