---
- name: Installiere apache2
  hosts: web
  remote_user: ansible
  become: true
  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=3600

  - name: Installiere apache2 in aktueller Version
    apt: name=apache2 state=latest

  - name: Setze neue index.html
    copy: src=index.html dest=/var/www/html/index.html
