Vagrant.configure("2") do |config|

  config.vm.box = "windows_2016_ansible_virtualbox"
  config.vm.network "private_network", ip: "172.16.2.30"

  config.vm.provider "virtualbox" do |virtualbox|
     virtualbox.name = "StuttgartWindows"
     virtualbox.gui = true
     virtualbox.memory = 2048
     virtualbox.cpus = 4
   end

end