Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = false
    config.vm.network "private_network", ip: "172.16.2.21"

    config.vm.provider :virtualbox do |virtualbox|
       virtualbox.name = "NewYorkUbuntu"
       virtualbox.gui = true
       virtualbox.memory = 1024
       virtualbox.cpus = 2
       virtualbox.customize ["modifyvm", :id, "--ioapic", "on"]
       virtualbox.customize ["modifyvm", :id, "--vram", "32"]
    end

end